# Projeto Final: análise das candidaturas da eleição de 2022

**Participantes:** Felipe Albanez de Oliveira

## Bases utilizadas
- **principal:** consulta_cand_2022_BRASIL.csv
- **auxiliar:**  consulta_cand_complementar_2022_BRASIL.csv

### 1. Importando as bibliotecas Pandas e Numpy

In [1]:
# Para facilitar no desenvolvimento, "apelidamos" as bibliotecas no momento da importação
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt

### 2. Criando o DataFrame com os dados do arquivo .csv

#### Erro na primeira tentativa de criação do DataFrame

In [ ]:
"""
# caminho Mac
#pasta_arquivo = "/Users/felipealbanez/Data Analytics/CAIXA Verso/Técnicas de Programação I (PY)/Projeto Final/Projeto Dados PRF 2025/datatran2025.csv"

# caminho Trabalho
pasta_arquivo = "/Users/c128271/OneDrive - Caixa Economica Federal/Área de Trabalho/CAIXA Verso/Projeto Final/Base de dados/consulta_cand_2022_BRASIL.csv"
df_original = pd.read_csv(pasta_arquivo)
df_original.head()

#  erro:
# UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 838: invalid continuation byte

"""

#### Segunda tentativa de criação do DataFrame

In [2]:
""""
Segunda tentativa - modo a "a brasileira"
sep=';': Os dados usam ponto e vírgula para separar as colunas
decimal=",": números decimais usam vírgula
encoding='latin-1': Evita erros de leitura com acentos e caracteres da língua portuguesa.
"""

# substitua o caminho abaixo pela pasta onde está salvo a base de dados .csv
# não esquecer que o nome do arquivo e extensão deve estar incluso

# caminho Mac
pasta_arquivo = "/Users/felipealbanez/Github/CAIXAVERSO_DFF/Projeto_Final_TSE_2022/bem_candidato_2022_BRASIL.csv"

# caminho Trabalho
# pasta_arquivo = "/Users/cxxxxxx/OneDrive - Caixa Economica Federal/Área de Trabalho/CAIXA Verso/Projeto Final/Base de dados/consulta_cand_2022_BRASIL.csv"

# cria o dataframe lendo o arquivo .csv
df_original = pd.read_csv(pasta_arquivo, sep=';', decimal=',',encoding='latin-1')

In [ ]:
# vizualisa as 5 primeiras linhas do dataframe
df_original.head()

### 3. Conhecendo o DataFrame

#### 3.1. Comandos usados para ver o tamanho e a estrutura do DataFrame

In [ ]:
# shape: informa o número de linhas e colunas
print(f'Shape: {df_original.shape}')
print(f'Quantidade de linhas: {df_original.shape[0]}')
print(f'Quantidade de colunas: {df_original.shape[1]}')

In [ ]:
# info: informa os tipos, faltantes, memória
df_original.info()

In [ ]:
# describe: faz um resumo das colunas
df_original.describe

#### 3.2. Verificação de Faltantes

In [28]:
# cria um df chamado Faltantes
# são criadas tres colunas para o df 
# isna.sum: percorre a coluna e retorna a soma dos faltantes
# isna.mean: percorre a coluna e retorna a média dos faltantes em relação ao número total de itens na coluna
# nunique: conta quantos valores diferentes cada coluna tem
faltantes = pd.DataFrame({
    'faltantes': df_prf_original.isna().sum(),
    '% faltantes': (df_prf_original.isna().mean() * 100).round(2),
    'distintos': df_prf_original.nunique(),
})

# filta somente as colunas que não possui faltantes
# sort e ascending: ordena pela coluna faltante do maior para o menor
faltantes[faltantes['faltantes'] > 0].sort_values('faltantes', ascending=False)

                        faltantes  % faltantes  distintos
uop                            38         0.05        395
delegacia                      22         0.03        153
regional                        2         0.00         28
classificacao_acidente          1         0.00          3

#### **Análise do resultado:**
O resultado eidência que a base de dados apresenta qualidade boa, uma vez que a quantidade de faltantes é baixíssima. 

As colunas que possuem valores distintos altos são dados de identificação, portanto estão ok. 

A conclusão é que não há necessidade de deletar linhas.

#### 3.3. Verificação de Duplicados

In [ ]:
# verifica se existe linhas com todos os dados duplicados
print('Linhas totalmente duplicadas:', df_prf_original.duplicated().sum())

# o id deve ser sempre único, portanto é necessário analisar possível duplicidade
print('IDs duplicados:', df_prf_original['id'].duplicated().sum())

# df filtrado somente com "id" duplicados
df_prf_original[df_prf_original.duplicated(keep=False)].sort_values('id').head(6)

Linhas totalmente duplicadas: 0
IDs duplicados: 0

Empty DataFrame
Columns: [id, data_inversa, dia_semana, horario, uf, br, km, municipio, causa_acidente, tipo_acidente, classificacao_acidente, fase_dia, sentido_via, condicao_metereologica, tipo_pista, tracado_via, uso_solo, pessoas, mortos, feridos_leves, feridos_graves, ilesos, ignorados, feridos, veiculos, latitude, longitude, regional, delegacia, uop]
Index: []

[0 rows x 30 columns]

#### 3.4. Categorias inconsistentes

In [ ]:
# retorna todas as colunas do df
df_prf_original.columns

Index(['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km',
       'municipio', 'causa_acidente', 'tipo_acidente',
       'classificacao_acidente', 'fase_dia', 'sentido_via',
       'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo',
       'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos',
       'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional',
       'delegacia', 'uop'],
      dtype='object')

In [ ]:
# verificação dos dias da semana
df_prf_original['dia_semana'].value_counts()

In [ ]:
# verificação da escrita dos estados
df_prf_original['uf'].value_counts()

In [ ]:
df_prf_original['classificacao_acidente'].value_counts()

### 3.5. Valores inválidos

### 4. Definindo quais colunas do Dataframe serão utililizadas

In [ ]:
# imprimi as colunas do df
print(df_prf_original.columns)

In [ ]:
# quais valores cada coluna possui
# unique: retorna uma lista com os valores únicos daquela coluna
# valeu_counts

uf = df_prf_original['uf'].unique()
print("uf:", uf)

df_prf_original['uf'].value_counts()

In [ ]:
# cria uma lista com os nomes das colunas

# colunas_selecionadas = []